### ISSUE TITLE
kESI electrode leadfield calculation using MFEM

### ISSUE THREAD

**Issue by mdovgialo** [Neuroinflab/kESI#17]
- change the engine of kESI from Fenics to one of
FenicsX https://fenicsproject.org/
MFEM https://mfem.org/

Start by recreating sphere solution from tutorial

**Comment by mdovgialo** [comment]
#17 trying out mfem

Managed to load our 4 spheres model, without ground place, experimenting with boundary conditions and poin charges. Right now only boundary conditions seem to work, not sure how:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/fe3803bf-72e5-4bd5-8eff-8e11897d8734)

![image](https://github.com/Neuroinflab/kESI/assets/6193380/d5029ce4-8bdc-4bd0-afde-a67d302e526c)

Making only the outside sphere have 0 potential results in zero potential everywhere, despite a point charge present...

![image](https://github.com/Neuroinflab/kESI/assets/6193380/f974ca59-7e01-4fe3-b617-b5bdc6108dd7)

Next:
try adding ground plane like in FENICS solver

**Comment by mdovgialo** [comment]
MFEM seems to have predefined (but flexible) integrators for different classes of differential equations. It might be an issue to write a custom equation to solve in python

**Comment by mdovgialo** [comment]
Solved a bug which didn't notice yesterday. Now 3 spheres with a point in it can look like this:

COefficients all equall 0.33

![image](https://github.com/Neuroinflab/kESI/assets/6193380/7f52a9af-6847-48b2-8e63-c935456c3f36)



coeeficients equal:
[0.33, 1.65, 0.0165, 0.33])

![image](https://github.com/Neuroinflab/kESI/assets/6193380/5b3acdb5-c746-435b-88cd-0d1340424aa8)

and coefficients which are reciprocity of above:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/94cf9d82-c3a0-4c18-812c-a3ce0bedf459)


Unity Point source on the side. Outside sphere has a boundary condition of being 0. Can't figure out how to add a grounding plane yet...

**Comment by mdovgialo** [comment]
Implemented solver, which seems to do the correct thing.
Implemented an experimental voxel based resampling of a point cloud of the solution, might not be needed for equally sampled volumetric solutions in spirit of "MRI as a hex mesh" . For now allows to decently sample any mesh at any resolution, smoothed with boxcar kernel of a size of biggest mesh element

We put an electrode on top of the brain, just below the skull/CSF.


First, let's look at analytic solution of assuming 

V_kcsd = 1.0 / (4 * np.pi * sigma_base * distance_to_electrode)

Which we define on vertices of vertices of the mesh we are using, and then sampled using voxel based resampling (kinda sanity check of a MFEM solution postprocessing methods):

![image](https://github.com/Neuroinflab/kESI/assets/6193380/190d245d-d5fe-493d-acd7-a5349b4133ff)

Contrast is set that at 10 Volts it's exactly white, so we can follow 10 Volt isolines. Cross is put on an isoline


sigma = 0.33.

Lets compare it with MFEM simulations of a point charge at the electrode positions, using 3 meshes:

1. 4 spheres in an air box, with grounding plate being a bottom surface of the box, just below the 4 shperes
2.  4 spheres in an air box, with grounding electrode in brain tissue
3.  4 spheres with a grounding electrode in brain
4.  4 spheres with a grounding electrode in skin 


To simulate point charges a DiffusionIntegrator, which solves poisson equation was used. Physical Volumes had assigned coefficients:

conductivities_vector = mfem.Vector(list(1.0 / (4 * np.pi * np.array([0.33, 1.65, 0.0165, 0.33, 1e-10]))))
(conductances, of brain matter, CSF, bone, skin, air (when model had air box))

Additionally a domain integrator was used to place a point charge using DeltaCoefficient.

#  4 spheres in an air box, with grounding plate

![image](https://github.com/Neuroinflab/kESI/assets/6193380/866ca1e6-4ed6-4cfb-b266-b4ae13c71873)

Contrast is set that at 10 Volts it's exactly white, so we can follow 10 Volt isolines. Cross is put on an isoline of analytical solution

![image](https://github.com/Neuroinflab/kESI/assets/6193380/1150318d-1e2c-43a2-adcd-c992a1609c88)

Contrast set to 1V so we can see the the effect of ground

#   4 spheres in an air box, with grounding electrode in brain tissue

![image](https://github.com/Neuroinflab/kESI/assets/6193380/8921d6f6-8468-4cc0-83aa-656e75f49e6a)

Contrast is set that at 10 Volts it's exactly white, so we can follow 10 Volt isolines. Cross is put on an isoline of analytical solution

![image](https://github.com/Neuroinflab/kESI/assets/6193380/0381b73f-339b-468e-afff-03b3c79b3638)

Contrast set to 1V so we can see the the effect of ground electrode

#  4 spheres with a grounding electrode in brain

![image](https://github.com/Neuroinflab/kESI/assets/6193380/fb9c7d64-f09d-4b23-b8da-c19b9e60eceb)

Contrast is set that at 10 Volts it's exactly white, so we can follow 10 Volt isolines. Cross is put on an isoline of analytical solution



![image](https://github.com/Neuroinflab/kESI/assets/6193380/f149b8c9-c144-4040-8eff-01b981e7dbe6)

Contrast set to 400V so we can see the the effect of ground electrode

We can see that without surrounding air, the potential inside the spheres is a lot higher

# 4 spheres with a grounding electrode in skin 

![image](https://github.com/Neuroinflab/kESI/assets/6193380/f82c3f5a-08fe-49e5-899c-af9924f720a9)

Contrast is set that at 10 Volts it's exactly white, so we can follow 10 Volt isolines. Cross is put on an isoline of analytical solution

![image](https://github.com/Neuroinflab/kESI/assets/6193380/abd1ae2b-f891-48d5-92d2-aeed1a428762)


Contrast set to 400V so we can see the the effect of ground electrode

The overall potential in the spheres is lower compared to electrode in the brain tissue, but still is way higher compared to free space analytical solution.

# Old FENICS/KESI leadfield correction potential

![image](https://github.com/Neuroinflab/kESI/assets/6193380/a1a9cc33-9ccd-4d0e-8e23-952b0fb5af51)

This image is a difference between FEM solution and free space solution. The mesh is 4 spheres without air, but with a forced infinte grounding plane touching the bottom of the spheres.

Let's try to have a more decent comparisson, by addign the free space solution to the leadfield:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/61d43638-67ed-47b8-9220-e730e858aa43)

Contrast is set that at 10 Volts it's exactly white, so we can follow 10 Volt isolines. Cross is put on an isoline of analytical solution. We can see that the whole sphere is way above 10 Volt line, except the part, where the sphere meets the grounding plate.

![image](https://github.com/Neuroinflab/kESI/assets/6193380/40f523d5-6ffe-4ba0-9bf5-6627586de3a7)

Contrast set at 400 volts, we can see the weird interpolation, slighly triangular in shape, which gets visible even better, if we just look at the  difference between FEM solution and free space solution, calculated by the FENICS zoomed in

![image](https://github.com/Neuroinflab/kESI/assets/6193380/05263fcb-2d81-44ec-b7ec-489601cdda7e)
We can  observe triangular, hexagonal artifacts with protrusions on connecting edges, which means, this image is sampled in a way higher resolution than the size of FEM elements (this was calculated using "fine" preset of KESI 4 spheres template)

# Conclusions?

As we can see We can recreate similar point source potential distribution, on way higher resolution meshes, than FENICS, with calculations taking a fraction of time. Mmesh with maximum element size of 0.005 meters (around 5 milion elements after refining) takes a dozen of seconds to simulate, and 30 to sample using KDTrees, and MFEM is not even compiled with CUDA or multithreading support.

There doesn't seem to be problems with the electrode position singularity. But lack of air volume in legacy KESI models, seems to elevate potential inside the sphere by orders of magnitude. Adding air box, makes the solution similar in shape and orders of magnitude to free space analytical (in the parts of isotropic, even material), and seem to have similar isolines at V=10, 20, but different at low voltages (1, 2 5). The isolines on the FEM solution are deformed by the mesh boundaries, which is what we wanted to see. 

Lack of air volume might have introduced elevated potential, and changed the profiles

# Todo
- [ ] calculate first electrode from FENICS tutorial on "finer" or "finest" and calculate the profile
- [x] compare potential a line section profile for original solution, free space solution, and new mfem solutions, on a line going vertically through the electrode position
- [ ] organize the  code from experimental into proper configurable script, which can read ini files with materials/conductivity definitions
- [ ] generate compatible with KESI leadfeald files
- [ ] compare KESI on 4 spheres with original and new leadfields





@danek8317 What do you think? I guess we'll discuss it on monday.

**Comment by mdovgialo** [comment]
![image](https://github.com/Neuroinflab/kESI/assets/6193380/1064b1de-cc78-483e-a1a0-ead96e4212e5)

comparison of profiles going vertically through 4 spheres through the electrode

**Comment by mdovgialo** [comment]
Comparison of potential of a point charge (electrode), calculated using new model at 0.002 m mesh resolution and FINEST fenics preset (first + potential):

![image](https://github.com/Neuroinflab/kESI/assets/6193380/0d5c2a5e-ffa6-4839-a617-dab156aaa7aa)

![image](https://github.com/Neuroinflab/kESI/assets/6193380/8e696b17-64da-4562-8962-6ad1125b63ba)

And the correction leadfield (potential from mesh - free space):

![image](https://github.com/Neuroinflab/kESI/assets/6193380/3700601c-a6d7-440f-b62c-8df06dcb12df)


![image](https://github.com/Neuroinflab/kESI/assets/6193380/0b0a7d86-8375-4089-878d-ffba256f0aed)

**Comment by mdovgialo** [comment]
All old sphere models had problems around electrode, except finest solution,  due to interpolation of a quite big mesh element.

Finest solution was more or less smooth


Leadfield (V_mesh - V_kCSD)

Fine: 

![image](https://github.com/Neuroinflab/kESI/assets/6193380/59565d28-a0b6-4d86-b48e-74837a056f26)


Finest (takes a long time to compute):

![image](https://github.com/Neuroinflab/kESI/assets/6193380/88ddc167-3b3e-4909-8889-347fa0725ae9)

MFEM with air and grounding plate at 0.002 m resolution

![image](https://github.com/Neuroinflab/kESI/assets/6193380/8bcd7164-ba5a-4810-8387-72b952bd3ea5)

MFEM without air with grounding electrode:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/571e0272-c4b1-4761-923e-8ac5def5daa7)


# Comparison of theoretical potential in free space and MFEM with air at 0.002

![image](https://github.com/Neuroinflab/kESI/assets/6193380/f518301f-388e-44ef-b023-d4b378dfbae2)

# Comparison of theoretical potential in free space and MFEM without air at 0.002

![image](https://github.com/Neuroinflab/kESI/assets/6193380/2270a2e6-9e8e-4727-81f5-e73ae63af0fc)


#  Comparison of theoretical potential in free space and old FENICs leadfield+V_kCSD at FINEST preset

![image](https://github.com/Neuroinflab/kESI/assets/6193380/cf956617-8a5d-4baa-bfa0-9201d6185224)

**Comment by mdovgialo** [comment]
Compared theoretical potential (V = 1 / (4 * pi * sigma * r)) calculated on a regular grid vs on a vertices of the mesh and voxel resampled

![image](https://github.com/Neuroinflab/kESI/assets/6193380/5ccbed20-5720-4cd7-a394-6ca9b131263c)

**Comment by mdovgialo** [comment]
Really, didn't like the results of voxel downsampling on 0.005 mesh

Researched a bit further and looked into pyvista https://docs.pyvista.org/version/stable/examples/01-filter/resample#resampling-example, which uses VTK to sample meshes.

Allows to resampling one mesh into another. Looks at the mesh element, and then interpolates value inside a mesh element based on the mesh element vertices. Allows us to preserve sharp transitions between boundaries and better samples theoretical line (calculated on the mesh vertices) too. We don't need to enforce extremely small elements universally anymore. Results a re also smoother and less noisy.


![image](https://github.com/Neuroinflab/kESI/assets/6193380/dab55303-c613-4063-aa92-e74f8fdbbc16)

![image](https://github.com/Neuroinflab/kESI/assets/6193380/0754d850-b3df-46aa-be88-49e56d72f0c4)

Note how purple and orange lines of vista resample sharply fall together at the skull boundary.

0.002 mesh mfem downsampling:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/347faa61-1c16-4075-9b60-e55a009460a6)

0.005 mesh mfem downsampling:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/a81409cf-2bd9-4f88-8202-5350ba8d17cb)

0.01 mesh mfem vista:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/d5ee5909-39e2-4656-95e9-6061223ca1b3)

0.005 mesh mfem vista:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/b54040f0-6b0e-4972-976a-9d04ba3d363e)

but at high potential cutoff 0.01 mesh is definitely not enough and creates artifacts in shape of mesh elements:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/63c50062-5a28-41ad-b69d-fefdc946c8c1)

need more mesh refinement or reduce maximum size.

**Comment by mdovgialo** [comment]
Cleaned up scripts, recreating tutorial

Checking to see if the exported correction leadfields are correct:

in the constructor.py `        return ssi.fftconvolve(LEADFIELD,
                               CSD * WEIGHTS,
                               mode='same')[self.src_idx('POT')]`

checking LEADFIELD for a electrode placed at:

x=0.5
y=0.5
z=0

Just a reminder, LEADFIELD is the difference of FEM solution and analytic solution.

As originally sampled using "normal" solution calculated by fenics using old meshes:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/31977e6f-6a43-489f-8d64-bfefa40b6432)

Increased sampling radius:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/939eda3c-b26e-4e4b-ab0f-2e49d6bda905)


Changed solver to MFEM, 4 sphere mesh in vacuum (like the old one, 0.005 m maximum mesh element)

![image](https://github.com/Neuroinflab/kESI/assets/6193380/f866570f-6860-44fd-a78c-4bdfa5a8abcc)

But now suspended in air, instead of vacuum:


![image](https://github.com/Neuroinflab/kESI/assets/6193380/31302b65-609a-407a-a3ea-09fc5cf2ecf5)



Comparison animation:

![leadfields_used_by_kesi](https://github.com/Neuroinflab/kESI/assets/6193380/2fc85a25-5fe5-4a81-8584-5b9b123543b7)

**Comment by mdovgialo** [comment]
To compare the solutions.

Based on `tutorial_four_spheres_mfem.ipynb`

We have 4 electrodes in 4 sphere model.

Ground truth:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/81146105-0cd1-49bd-a648-dc3c5624b073)

Potentials are calculated using FENICS modeling on a 4 sphere model in vacuum.

kESI solution using FENICs calculated leadfields 4 sphere model in vacuum:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/b55bd4a9-1742-4c05-8e63-22a994ba03fb)

kESI solution using MFEM calculated leadfields, 4 sphere model in vacuum:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/b2071460-17ae-4dfe-9367-083faf5e7923)

kESI solution using MFEM calculated leadfields, 4 sphere model suspended in air:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/8254f398-f371-4a6c-a49b-2b62771c81c6)


kCSD solution:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/f8383cb7-af9d-4b6b-81ef-647fc76986e0)

kESI solution, but each electrode corrective leadfield is 0 outsidee the 4 spheres and exactly 100 inside of the 4 spheres

![image](https://github.com/Neuroinflab/kESI/assets/6193380/6b3779e9-2183-4c31-9500-0bf77e64886c)

Better than kCSD, better than 4 spheres in air.

Maybe the old tutorial is using the corrections wrong? Maybe it's treating them as potentials instead of analytical-numerical difference?



## Test instead of correction (v_anal - v_mesh) we just use mesh potential

kESI, vacuum:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/a5d2bd64-dae8-4544-9401-6fcd1b85a1a0)


kESI, air:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/11eb5ff1-2fb7-45b7-9846-20423d67d207)

**Comment by mdovgialo** [comment]
TODO:

Check how exactly leadfield correction is used, should it really be the difference between analytic and FEM solution?
Check for analytical 4 spheres solution?
